### PR TITLE
Body parameters 

### PR DESCRIPTION
**Pull request by Jorgevillada**
Adding support for body parameters (variables): [https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Channels+REST+API#Asterisk13ChannelsRESTAPI-list](https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Channels+REST+API#Asterisk13ChannelsRESTAPI-list).

### CODE REVIEW

**Comment by l3nz** [comment]
I am not sure I am okay accepting a patch to autogen code. 
But we can do better - I am currently rewriting the code generator, so maybe we can find a default way to do that?

You are only thinking about 
`originate: POST /channels
`
correct?

**Comment by Jorgevillada** [comment]
So far I have only seen in / channels. I do not know if there are other methods. also I saw the body parameters can be interpreted also as query parameters.

".. Other keys in the body object query parameters are Interpreted as Ex {" endpoint ":" SIP / Alice "," variables ": {" CALLERID (name) ":" Alice "}}".

I do not know if in the following versions of ARI plan to leave only body parameters.

**Comment by sebmurrayqi** [comment]
So I guess I just created a Pull Request to do the same thing :P Perhaps I should have checked the Pull Requests first.

My change works for any number of parameters or functions, there was only a minor change required to the code generator as it was mostly set up already to handle parameters. The only issue was actually adding the parameters in the map to the actual body of the request. I have tested this in development and it works quite nicely. The client I am working with will be doing some extended testing over the next week or so

@l3nz  I guess you get to choose which one you would rather use :)

**Comment by l3nz** [comment]
I just merged @sebmurrayqi 's patch, that should have the same functionality.

**Pull request closed without merging**
