### PR TITLE
Auto reconnect fixes

### PR DESCRIPTION
**Pull request by grahambrown11**
Hi Lenz

We've been experiencing some issues with the auto reconnect not releasing handles, eventually after a few auto reconnects we're not able to create new connections...
I've spent some time and found the issues here are my corrections :-)

Thanks
Graham

### CODE REVIEW

**Comment by l3nz** [comment]
Done!

**Comment by l3nz** [comment]
Release 0.4.3

**Comment by grahambrown11** [comment]
Thanks for merging, any idea when bintray will have 0.4.3?

**Comment by l3nz** [comment]
Should be there now. DO you see it? (I had some Bintray errors)

**Pull request merged**
